export type RootStackParamList = {
  Login: undefined;
  Register: undefined;
  RegisterDetails: undefined;
  EmailConfirmed: undefined;
  ForgotPassword: undefined;
  LocationSetup: undefined;
  Home: { tab?: "ontdekken" | "connecties" } | undefined;
  Match: { matchId: string; matchedName: string; matchedPhoto: string; matchedUserId: string };
  Filter: undefined;
  SporterProfile: { sporterId: string };
  Profile: undefined;
  EditProfile: undefined;
  Menu: undefined;
  ChatList: undefined;
  ChatDetail: { chatId: string; name: string; photo: string; otherUserId: string };
  PostsFeed: undefined;
  NewPost: { eventDate?: string } | undefined;
  Settings: undefined;
  Pricing: undefined;
  Payment: { plan: "premium" | "elite" };
  Helpdesk: undefined;
  Faq: undefined;
  Support: undefined;
  ChangeEmail: undefined;
};
